// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MySalesTracker.Infrastructure.Persistence;

#nullable disable

namespace MySalesTracker.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260828132803_SimplifyPriceRules")]
    partial class SimplifyPriceRules
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MySalesTracker.Domain.Entities.Event", b =>
                {
                    b.Property<int>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EventId"));

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("EventId");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("MySalesTracker.Domain.Entities.EventDay", b =>
                {
                    b.Property<int>("EventDayId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EventDayId"));

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<decimal?>("StartingPettyCash")
                        .HasColumnType("decimal(8,2)");

                    b.Property<int>("StartingPettyCashCurrency")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("EventDayId");

                    b.HasIndex("EventId");

                    b.ToTable("EventDays");
                });

            modelBuilder.Entity("MySalesTracker.Domain.Entities.Expense", b =>
                {
                    b.Property<int>("ExpenseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ExpenseId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(6,2)");

                    b.Property<int>("Currency")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("EventDayId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("ExpenseId");

                    b.HasIndex("EventDayId");

                    b.ToTable("Expenses");
                });

            modelBuilder.Entity("MySalesTracker.Domain.Entities.Payment", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(6,2)");

                    b.Property<int>("Currency")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("EventDayId")
                        .HasColumnType("int");

                    b.Property<int>("Method")
                        .HasColumnType("int");

                    b.HasKey("PaymentId");

                    b.HasIndex("EventDayId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("MySalesTracker.Domain.Entities.PriceRule", b =>
                {
                    b.Property<int>("PriceRuleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PriceRuleId"));

                    b.Property<int>("Currency")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(6,2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<int>("UnitsPerSale")
                        .HasColumnType("int");

                    b.HasKey("PriceRuleId");

                    b.HasIndex("ProductId")
                        .IsUnique()
                        .HasFilter("[IsDefault] = 1");

                    b.HasIndex("ProductId", "Price")
                        .IsUnique();

                    b.ToTable("PriceRules");
                });

            modelBuilder.Entity("MySalesTracker.Domain.Entities.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ProductId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("MySalesTracker.Domain.Entities.Sale", b =>
                {
                    b.Property<int>("SaleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SaleId"));

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("Currency")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<decimal>("DiscountValue")
                        .HasColumnType("decimal(6,2)");

                    b.Property<int>("EventDayId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(6,2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("QuantityUnits")
                        .HasColumnType("int");

                    b.HasKey("SaleId");

                    b.HasIndex("EventDayId");

                    b.HasIndex("ProductId");

                    b.ToTable("Sale");
                });

            modelBuilder.Entity("MySalesTracker.Domain.Entities.EventDay", b =>
                {
                    b.HasOne("MySalesTracker.Domain.Entities.Event", "Event")
                        .WithMany("Days")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");
                });

            modelBuilder.Entity("MySalesTracker.Domain.Entities.Expense", b =>
                {
                    b.HasOne("MySalesTracker.Domain.Entities.EventDay", "EventDay")
                        .WithMany("Expenses")
                        .HasForeignKey("EventDayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EventDay");
                });

            modelBuilder.Entity("MySalesTracker.Domain.Entities.Payment", b =>
                {
                    b.HasOne("MySalesTracker.Domain.Entities.EventDay", "EventDay")
                        .WithMany("Payments")
                        .HasForeignKey("EventDayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EventDay");
                });

            modelBuilder.Entity("MySalesTracker.Domain.Entities.PriceRule", b =>
                {
                    b.HasOne("MySalesTracker.Domain.Entities.Product", "Product")
                        .WithMany("PriceRules")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("MySalesTracker.Domain.Entities.Sale", b =>
                {
                    b.HasOne("MySalesTracker.Domain.Entities.EventDay", "EventDay")
                        .WithMany("Sales")
                        .HasForeignKey("EventDayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MySalesTracker.Domain.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EventDay");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("MySalesTracker.Domain.Entities.Event", b =>
                {
                    b.Navigation("Days");
                });

            modelBuilder.Entity("MySalesTracker.Domain.Entities.EventDay", b =>
                {
                    b.Navigation("Expenses");

                    b.Navigation("Payments");

                    b.Navigation("Sales");
                });

            modelBuilder.Entity("MySalesTracker.Domain.Entities.Product", b =>
                {
                    b.Navigation("PriceRules");
                });
#pragma warning restore 612, 618
        }
    }
}
