<Project Sdk="Microsoft.NET.Sdk">

  <Sdk Name="Aspire.AppHost.Sdk" Version="9.5.0" />

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>6970513b-11b8-4ddb-84f8-ab58c3fe46c3</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.AppHost" />
    <PackageReference Include="Aspire.Hosting.DevTunnels" />
    <PackageReference Include="Aspire.Hosting.SqlServer" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MySalesTracker.AspireServiceDefaults\MySalesTracker.AspireServiceDefaults.csproj" />
    <ProjectReference Include="..\MySalesTracker.Web\MySalesTracker.Web.csproj" />
  </ItemGroup>

</Project>
